api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "layaway-cart-transform"
type = "function"
uid = "c4de8eb0-6515-a03f-03a9-25c5d5164085d7a47dca"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
